---  
- hosts: localhost  
  gather_facts: no  
  tasks:  
    - name: create key pair  
      local_action:  
        module: ec2_key  
        region: "{{ region }}"
        name: "{{ keyname }}"
#        state: absent
      register: mykey
    - name: write to file
      local_action: shell echo -e "{{ item.value.private_key }}" > ~/.ssh/"{{ keyname }}".pem && chmod 600 ~/.ssh/"{{ keyname }}".pem
      with_dict: "{{mykey}}"
      when: item.value.private_key is defined
