---  
  - name: SECURITY GROUP | Create rds mysql security group
    ec2_group:
      name: "{{ tagname }}_rds_security_group"
      description: "{{ tagname }} rds security group"
      region: "{{ region }}"
      vpc_id: "{{ vpc.vpc_id }}"
      rules:
        - proto: tcp
          from_port: 3306
          to_port: 3306
          group_id: "{{ basic_ssh.group_id }}"
        - proto: tcp
          from_port: 3306
          to_port: 3306
          group_id: "{{ internal_sg.group_id }}"
    register: rds_sg
  - name: RDS | Create rds mysql instance
    rds:
      command: create
      region: "{{ region }}"
      instance_name: "{{ tagname }}-database"
      subnet : "{{ rds_sg.group_id }}"
      db_engine: MySQL
      engine_version: 5.6.27
      size: 100
      instance_type: db.t2.micro
      multi_zone: yes
      username: ctRootUser
      password: Ph0t0230311!
      db_name: "{{ prefix }}"
      tags:
        Environment: "{{ envParam }}"
        Application: "{{ prefix }}"