---  
  - name: NETWORK | create vpc with multi-az subnets   
    local_action:  
      module: ec2_vpc     
      region: "{{ region }}"
      cidr_block: 10.0.0.0/16
      resource_tags: '{"Name":"{{ prefix }}_vpc"}'
      subnets:
        - cidr: 10.0.0.0/24
          az: "{{ az0 }}"
          resource_tags: '{"Name":"{{ prefix }}_subnet_public"}'
        - cidr: 10.0.1.0/24
          az: "{{ az1 }}"
          resource_tags: '{"Name":"{{ prefix }}_subnet_private"}'
      internet_gateway: True
      route_tables:
          - subnets:
              - 10.0.0.0/24
            routes:
              - dest: 0.0.0.0/0
                gw: igw
    register: vpc
  - name: INFO | write vpc id to {{ prefix }}_vpc_info file
    local_action: shell echo "{{ prefix }}"_vpc":" "{{ vpc.vpc_id }}" > info/"{{ prefix }}"_vpc_info
  - name: INFO | write subnets id to {{ prefix }}_vpc_info file
    local_action: shell echo "{{ item.resource_tags.Name }}"":" "{{ item.id }}" 
                    >> info/"{{ prefix }}"_vpc_info
    with_items: "{{ vpc.subnets }}"
  - name: ELASTIC IP | allocate a new elastic IP without associating it to anything - 1
    ec2_eip: in_vpc=yes reuse_existing_ip_allowed=yes state=present region="{{ region }}"
    register: eip
  - name: INFO | output vpc info
    debug: msg="VPC info  is {{ vpc }}"
  - name: INFO | output the IP
    debug: msg="Allocated IP is {{ eip.public_ip }} , Allocation ID is {{ eip.allocation_id }} "
  - pause: prompt="Waiting 45 seconds for ELASTIC IP allocation" seconds=45
  - name: NETWORK | Create NAT instance for public subnet
    shell: "aws ec2 create-nat-gateway --region {{ region }} --subnet-id {{vpc.subnets[0].id}} --allocation-id {{ eip.allocation_id }}"
    register: nat_instance_raw
  - name: INFO | output the NAT gateway
    debug: msg="NAT gateway info {{ nat_instance_raw }} "
  - set_fact:
      nat_instance_json: "{{ nat_instance_raw.stdout|from_json }}"
  - set_fact:
      nat_instance: "{{ nat_instance_json.NatGateway.NatGatewayId }}"
  - name: INFO | output the NAT gateway
    debug: msg="NAT id {{ nat_instance }} "
  - name: NETWORK | Create new route table for the private subnet
    shell: "aws ec2 create-route-table --region {{region}} --vpc-id {{vpc.vpc_id}}"
    register: routetable_private_raw
  - set_fact:
      routetable_private_json: "{{ routetable_private_raw.stdout|from_json }}"
  - set_fact:
      routetable_private: "{{ routetable_private_json.RouteTable.RouteTableId }}"
  - name: NETWORK | Associate route table with private subnet 1
    shell: "aws ec2 associate-route-table --region {{region}} --route-table-id {{routetable_private}} --subnet-id {{vpc.subnets[1].id}}"
  - name: NETWORK | Create NAT route record for  private subnet 1
    shell: "aws ec2 create-route --region {{region}} --route-table-id {{routetable_private}} --destination-cidr-block '0.0.0.0/0' --nat-gateway-id {{nat_instance}}"

