---  
  - name: SECURITY GROUP | Create bastion ssh security group
    ec2_group:
      name: "{{ tagname }}_bastion_security_group"
      description: "{{ tagname }} bastion ssh security group"
      region: "{{ region }}"
      vpc_id: "{{ vpc.vpc_id }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
    register: basic_ssh
  - ec2:
      key_name: "{{ keyname }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      group_id: "{{ basic_ssh.group_id }}"
      image: "{{ ami_id }}"
      wait: yes
      instance_tags:
          name: "{{ tagname }}"
      vpc_subnet_id: "{{ vpc.subnets[0].id }}"
      assign_public_ip: yes
    register: ec2_bastion
